version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "quarterly"
  - package-ecosystem: "julia"
    directories: ["/",  "/docs", "/test"]
    schedule:
      interval: "monthly"
    groups:
      all-julia-packages:
        patterns:
          - "*"
