[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
MonteCarloScattering = "a575b980-c6d2-47bc-bd50-9f2bfd7764b5"

[compat]
Documenter = "1"
DocumenterCitations = "1"

[sources]
MonteCarloScattering = {path = ".."}
